pgtop: add test for required binaries
Signed-off-by: Sylvain Rabot <sylvain.rabot@f-secure.com>

diff --git a/bin/pgtop b/bin/pgtop
--- a/bin/pgtop
+++ b/bin/pgtop
@@ -56,6 +56,17 @@ eval set -- "$ARGV"
 
 # ------------------------------------------------------------------------------
 
+if [ -z "$(which psql)" ]; then
+    echo >&2 \"psql\" not found.
+    exit 1
+fi
+
+if [ -z "$(which watch)" ]; then
+    echo >&2 \"watch\" not found.
+    exit 1
+fi
+
+# ------------------------------------------------------------------------------
 
 while true ;
 do
